### ISSUE TITLE
QA (unit tests, CI), documentation

### ISSUE THREAD

**Issue by jmfrancois** [atom2ueki/react-drawer#1]
I plan to use react-drawer but I need the following changes so I will do theses.
Because I like opensource and I hate doing things alone, I would like to know if you are ok with theses changes:

* add tests
* add linters
* add documentation
* use animate.css as a dependency
* provide examples throw github pages (not in the master branch)
* make it works in my current project

**Comment by atom2ueki** [comment]
thank you for your interest @jmfrancois , yes, I'm glad to help add those things, and I'm always happy someone can help contribute on open source project, this weekend I have time work on it, and hopes we can continue maintain this repo using our spare time

**Comment by jmfrancois** [comment]
Hi @atom2ueki . Your welcome.

Just to be sure, I'm using react at work (& I need a drawer in my current project)
so I don't do that on my spare time.

If you don't have enough time to spend on this project later I would be glade to maintain it.

**Comment by atom2ueki** [comment]
Hi @jmfrancois, I can add you to collaborator later after I merge your current PR, but you still working on current pull request right, I've read through your code already, so just let me know when you finish this, thank you.

**Comment by jmfrancois** [comment]
You can merge, I have finished the first steps. I will continue later on it by adding better size and theming support.

This will be in september.

Holidays are coming for me :)
