### ISSUE TITLE
css style not attached with webpack

### ISSUE THREAD

**Issue by neekey** [atom2ueki/react-drawer#12]
Hi, I was trying to get this module work with my webpack project, it rendered successfully but without any CSS attached to the elements:

![image](https://cloud.githubusercontent.com/assets/499870/20921505/657e3a54-bbdf-11e6-8ac9-b4662d6f264c.png)

The way I used this module:

```js
import Drawer from 'react-drawer';

...

<Drawer
    open={this.state.openMenu}
    onClose={this.handleMenuCloseRequest} >...</Drawer>)
```

- `react-drawer`: `1.2.5`
- `react`:  `15.4.1`

**Comment by jmfrancois** [comment]
Could you show us your webpack config ?

**Comment by atom2ueki** [comment]
@neekey close the issue because of no response, you can always reopen the issue if you still encounter the problem

**Comment by ekeuus** [comment]
Hi! I have the same issue. I've attached my webpack config below.


`var rucksack = require('rucksack-css')
var webpack = require('webpack')
var path = require('path')

module.exports = {
  context: path.join(__dirname, './client'),
  entry: {
    jsx: './index.js',
    html: './index.html',
    vendor: [
      'react',
      'react-dom',
      'react-redux',
      'react-router',
      'react-router-redux',
      'redux'
    ]
  },
  output: {
    path: path.join(__dirname, './static'),
    filename: 'bundle.js',
  },
  module: {
    loaders: [
      {
        test: /\.html$/,
        loader: 'file?name=[name].[ext]'
      },
      {
        test: /\.css$/,
        include: /client/,
        loaders: [
          'style-loader',
          'css-loader?modules&sourceMap&importLoaders=1&localIdentName=[local]___[hash:base64:5]',
          'postcss-loader'
        ]
      },
	  {
        test: /\.less$/,
      	loaders: ["css-loader", "less-loader"]
      },
      {
        test: /\.css$/,
        exclude: /client/,
        loader: 'style!css'
      },
      {
        test: /\.(js|jsx)$/,
        exclude: /node_modules/,
        loaders: [
          'react-hot',
          'babel-loader'
        ]
      },
    ],
  },
  resolve: {
    extensions: ['', '.js', '.jsx']
  },
  postcss: [
    rucksack({
      autoprefixer: true
    })
  ],
  plugins: [
    new webpack.optimize.CommonsChunkPlugin('vendor', 'vendor.bundle.js'),
    new webpack.DefinePlugin({
      'process.env': { NODE_ENV: JSON.stringify(process.env.NODE_ENV || 'development') }
    })
  ],
  devServer: {
    contentBase: './client',
    hot: true
  }
}
`
