### ISSUE TITLE
React Drawer not showing

### ISSUE THREAD

**Issue by rachel-singh** [atom2ueki/react-drawer#13]
I have the following situation where even when the open property is toggle to true the drawer stays hidden.
As in the hiddenDrawer state does not change.

**Comment by atom2ueki** [comment]
@rachel-singh can you show me snippet of your code on this problem part?

**Comment by rachel-singh** [comment]
Toni,

This turned out to be a problem with me not initiating the control correctly on load. Once I fixed that it works just fine.

Thanks for providing the library.
Rachel



Sent via the Samsung Galaxy S® 6 edge, an AT&T 4G LTE smartphone


-------- Original message --------
