### ISSUE TITLE
Module not found: Can't resolve 'React' in react-drawer/lib

### ISSUE THREAD

**Issue by gregkowalski** [atom2ueki/react-drawer#18]
I tried creating a simple example app using create-react-scripts and react-drawer but it fails when I run `npm start` with the following error:

```
./node_modules/react-drawer/lib/react-drawer.js
Module not found: Can't resolve 'React' in '..../react-drawer-test/node_modules/react-drawer/lib'
```

I also tried to clone the source repo, build it and run the example app but got the same error.  I'm on Ubuntu 16.04 with npm 5.7.1.

**Comment by yadavsunil00001** [comment]
Hi, getting the same error, look like some recent issue. if you got something let me know

**Comment by jseparovic** [comment]
I get Module not found: 
```
./node_modules/react-drawer/lib/react-drawer.js
Module not found: `.../app/node_modules/React/index.js` does not match the corresponding path on disk `react`
```

**Comment by atom2ueki** [comment]
@gregkowalski did you run `npm install`, `npm run build`, `npm start` in sequence when you try the demo?

**Comment by atom2ueki** [comment]
@gregkowalski @yadavsunil00001 @jseparovic I believe it's causing by library webpack configuration, will rebuild it with new configure and release

**Comment by atom2ueki** [comment]
update version to v1.3.4
