### ISSUE TITLE
Module with equal name if case ignored

### ISSUE THREAD

**Issue by B-Stewart** [atom2ueki/react-drawer#4]
So I found an issue when I use this with webpack and other react packages because your require statements use a require('React') with a capital letter and everything else uses require('react') with a lower case letter. I was able to fix all the warnings by changing your code to:

`(function webpackUniversalModuleDefinition(root, factory) {
	if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory(require("react"));
	else if(typeof define === 'function' && define.amd)
		define(["react"], factory);
	else if(typeof exports === 'object')
		exports["ReactDrawer"] = factory(require("react"));
	else
		root["ReactDrawer"] = factory(root["react"]);
})(this, function(__WEBPACK_EXTERNAL_MODULE_3__) {`

Otherwise this looks like a really nice component.

**Comment by atom2ueki** [comment]
@B-Stewart Thanks for your interesting on this react component, you can do pull request on the changes, we will test and see

**Comment by B-Stewart** [comment]
#6 
Made a pull request.

**Comment by atom2ueki** [comment]
@B-Stewart thank you
