### ISSUE TITLE
how close the drawer if it opens another

### ISSUE THREAD

**Issue by artsx** [atom2ueki/react-drawer#5]
Hello,

I have several drawer in the menu (for example: notifications, visitors etc. ..).
I can run the componants but I would like when I open one, it closes the other if already open

Any idea ?

Best regards,

**Comment by atom2ueki** [comment]
@artsx you always can control a drawer outside from the box, because we have position, onClose, noOverlay, so you can tie these to your own controller functions, then, those final result will pass to the different ReactDrawer component

**Comment by artsx** [comment]
@atom2ueki Thank you for the tip, I hadn't thought of!
