### ISSUE TITLE
Pin or dock the drawer (for larger screens)

### ISSUE THREAD

**Issue by pureux** [atom2ueki/react-drawer#8]
I'm looking for a drawer solution that allows the user to pin/dock the drawer into an open position so it's always visible, on larger screens.  Is this difficult to implement with your current solution?  It doesn't seem to have any specific hooks for that, but is it possible with what is exposed currently?

**Comment by atom2ueki** [comment]
@pureux it's quite easy, just set `open` prop always true
```
<ReactDrawer
          open=true
...
```
but I don't understand your last question, can you explain more?

**Comment by pureux** [comment]
@atom2ueki thanks for the feedback; I was referring to having the sidebar dock side-by-side with the content instead of overlaying, when the screen is larger than X amount (but on smaller screens still doing the overlay).  There are some other React drawer solutions that have that capability, but the DOM structure is different for those and can be problematic with certain scrolling scenarios, or more specifically with a fixed app header.  However, those solutions handle the docking vs overlaying determination for you by just having an overridable pixel amount for the screen size to determine between the two and the rest is managed within the library.

Ultimately I found a way to do what I want with it, using a different library.  Thanks again for responding!
