### ISSUE TITLE
semantic release

### ISSUE THREAD

**Issue by jmfrancois** [atom2ueki/react-drawer#9]
Hi,

I'm using semantic release process on all addons I'm writing.
I would like to setup this on react-drawer.
The only constraints for you is to follow guidelines on the commit messages
- starts with **feat** -> trigger a feature release
- starts with **fix** -> trigger a minor release
- BREAKING CHANGE in the body -> trigger a major release

MAJOR dot FEATURE dot MINOR is what semver propose.

the idea behind semantic release is to add a semantic to the commit message.

Are you OK with this ?

Look at commits of thoses addons (the [CONTRIBUTING.md](https://github.com/Talend/react-cmf/blob/master/CONTRIBUTING.md#-git-commit-guidelines) file explains this in details):

https://github.com/talend/react-cmf/commits
https://github.com/talend/react-talend-components/commits
https://github.com/talend/react-talend-containers/commits
https://github.com/talend/bootstrap-theme/commits
https://github.com/jmfrancois/react-storybook-cmf/commits

Once we merge a pull request, the release is done by the CI

If you said yes, I can do the setup for you @atom2ueki

**Comment by atom2ueki** [comment]
@jmfrancois sure, let's do in this way, thank you

**Comment by atom2ueki** [comment]
@jmfrancois I can try to setup by myself if you haven't finished this enhancement

**Comment by jmfrancois** [comment]
I just didn't see your first answers sorry.

The only things I can't do is setup the tokens on travis.

Could you do this please for react-drawer ?

https://www.evernote.com/l/AJCdFgoRGmxHOJOEDF_7VW4qJN7HhWlQxEg

**Comment by jmfrancois** [comment]
Sorry @atom2ueki but you don't have added the tokens as mentionned here:
https://www.evernote.com/shard/s144/sh/9d160a11-1a6c-4738-9384-0c5ffb556e2a/24dec7856950c448

look at those logs
https://travis-ci.org/atom2ueki/react-drawer/jobs/174097481#L1268
```shell
semantic-release ERR! init No github token specified. ENOGHTOKEN
semantic-release ERR! init No npm token specified. ENONPMTOKEN
```

to get your npm token you can get it on your .npmrc file in your home folder

more ~/.npmrc
//registry.npmjs.org/:_authToken=THE CORRESPONDING TOKEN

for github you can get it on https://github.com/settings/tokens

**Comment by atom2ueki** [comment]
@jmfrancois my bad, just done the setup, should be ok now, but check with you, shall we use GITHUB_TOKEN environment variables instead of GH_TOKEN, or it doesn't matter ?

**Comment by jmfrancois** [comment]
Oh thanks that step is now OK.
But here is a new error:
https://travis-ci.org/atom2ueki/react-drawer/jobs/174097481#L1271

```shell
semantic-release ERR! commits The commit the last release of this package was derived from is not in the direct history of the "master" branch.
semantic-release ERR! commits This means semantic-release can not extract the commits between now and then.
semantic-release ERR! commits This is usually caused by force pushing, releasing from an unrelated branch, or using an already existing package name.
semantic-release ERR! commits You can recover from this error by publishing manually or restoring the commit "d1c51110ec27190d3a8d42af1ccd57941c2ee9d3".
semantic-release ERR! pre Failed to determine new version.
semantic-release ERR! pre ENOTINHISTORY Commit not in history
```

Often to fix this here is what I'm used to do.

let's think the new version is 1.2.5
```shell
git checkout master
git pull origin master
vim package.json (to add "version": "1.2.5", in a new line)
git tag v1.2.5
npm publish
git push --tags
git checkout package.json
```

Because of semantic-release you have to be sure to never commit the version in the package.json

**Comment by atom2ueki** [comment]
@jmfrancois I see, because previously I never do `git push origin master --tags` before `npm publish`
